## Weather Observation Station 3
__Q.__ STATION 테이블에서 ID가 짝수(even number)인 것만 출력, 중복은 허용하지 않음

In [ ]:
#1
SELECT DISTINCT CITY FROM STATION
WHERE MOD(ID, 2) = 0;

#2
SELECT DISTINCT CITY FROM STATION
WHERE (ID % 2) = 0;

## Weather Observation Station 4
__Q.__ STATION 테이블에서 전체 CITY와 중복을 제거한 CITY를 뺀 값을 조회하기

In [ ]:
SELECT COUNT(CITY) - COUNT(DISTINCT CITY) FROM STATION;

## Weather Observation Station 5
__Q.__ STATION 에서 가장 짧은 CITY 이름과 가장 긴 CITY 이름 조회
- 가장 작거나 큰 도시가 두개 이상인 경우, 알파벳 순으로 정렬할 때 먼저 오는 도시를 선택

In [ ]:
SELECT CITY, LENGTH(CITY) FROM STATION
ORDER BY LENGTH(CITY) ASC, CITY ASC
LIMIT 1;

SELECT CITY, LENGTH(CITY) FROM STATION
ORDER BY LENGTH(CITY) DESC, CITY ASC
LIMIT 1;

## Weather Observation Station 7
__Q.__ CITY이름 중 (a, e, i, o, u)로 끝나는 CITY를 조회
- 중복은 제외

In [ ]:
SELECT DISTINCT CITY FROM STATION
WHERE CITY LIKE '%a' or CITY LIKE '%e' or CITY LIKE '%i' or CITY LIKE'%o' or CITY LIKE '%u';

## Weather Observation Station 8
__Q.__ CITY의 양 끝이 (a, e, i, o, u)로 끝나는 도시를 조회
- 중복은 허용하지 않음

In [ ]:
SELECT DISTINCT CITY FROM STATION
WHERE CITY REGEXP'^[aeiou]'
AND CITY REGEXP'[aeiou]$';

## Weather Observation Station 9
__Q.__ CITY의 이름이 (a, e, i, o, u)로 시작하지 않는 도시의 이름을 조회
- 중복을 허용하지 않음

In [ ]:
SELECT DISTINCT CITY FROM STATION
WHERE NOT CITY REGEXP '^[aeiou]';

## Weather Observation Station 10
__Q.__ CITY의 이름이 (a, e, i, o, u)로 끝나지 않는 도시의 이름을 조회
- 중복을 허용하지 않음

In [ ]:
SELECT DISTINCT CITY FROM STATION
WHERE NOT CITY REGEXP '[aeiou]$';

## Higher Than 75 Marks
__Q.__ STUDENTS테이블에서 75Marks가 넘는 학생의 이름을 조회
- 이름의 뒤에서 3개를 가지고 오름차순 정렬하고, 뒤의 3글자가 같으면, ID로 오름차순 정렬

🐾 부분 문자열 가져오기
- LEFT(컬럼명, n) : 왼쪽을 기준으로 n개의 문자를 가져오는 함수
- RIGHT(컬럼명, n) : 오른쪽을 기준으로 n개의 문자를 가져오는 함수
- MID(컬럼명, 시작위치, n) : 지정한 시작위치를 기준으로 n개의 문자를 가져오는 함수

In [ ]:
SELECT NAME FROM STUDENTS
WHERE MARKS > 75
ORDER BY RIGHT(NAME, 3) ASC, ID ASC;

## Type of Triangle
__Q.__  세 변의 길이를 사용하여 TRIANGLES 테이블 의 각 레코드 유형 을 식별하는 쿼리를 작성
- 코드에 대해 다음 명령문 중 하나를 출력함
 - Equilateral: It's a triangle with  sides of equal length.
 - Isosceles: It's a triangle with  sides of equal length.
 - Scalene: It's a triangle with  sides of differing lengths.
 - Not A Triangle: The given values of A, B, and C don't form a triangle.
  <br>
  ⏰ 두 변의 합이 한 변보다 작거나 같을 경우 삼각형이 성립되지 않음

- 조건문 사용
  - __CASE WHEN__ 조건문 __THEN__ '표시할 것' __ELSE__ '표시할 것' __END__

In [ ]:
SELECT 
CASE 
WHEN A = B AND B = C THEN 'Equilateral'
WHEN A + B <= C OR A + C <= B OR B + C <= A THEN 'Not A Triangle'
WHEN A = B OR A = C OR B = C THEN 'Isosceles'
ELSE 'Scalene'
END
FROM TRIANGLES;

## Revising Aggregations - Averages
__Q.__ District가 California인 곳의 인구율 평균 구하기

- __AVG()__연산자 이용

In [ ]:
SELECT AVG(POPULATION) FROM CITY
WHERE DISTRICT = 'California'

## Weather Observation Station 15
__Q.__ STATION테이블에서 LAT_N이 137.2345보다 작고, 그 범위안에서 LAT_N이 가장 큰 LONG_W를 반올림 4한 값을 구하기

In [ ]:
SELECT ROUND(LONG_W, 4) FROM STATION
WHERE LAT_N < 137.2345
ORDER BY LAT_N DESC
LIMIT 1;